apiVersion: canarying.mozilla.com/v1alpha1
kind: CanaryDeployment
metadata:
  name: app
  labels:
    app: app
spec:
  metrics:
    - kind: httpErrorRate
  deploymentTemplate:
    # This is basically copy pasted from the deployment.
    # It should be filled in by whatever we use for templating.
    minReadySeconds: 5
    metadata:
      name: app-deployment
      labels:
        app: app
    spec:
      selector:
        matchLabels:
          app: app
      template:
        metadata:
          labels:
            app: app
        spec:
          containers:
          - name: app
            image: app:good
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 80
                name: web

